// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvvtmsykjeyrevjmofhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2dnRtc3lramV5cmV2am1vZmhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NzQ1MDksImV4cCI6MjA2ODU1MDUwOX0.C0LvLDh57qMaAwi_yQmbhIM1lm2RmTeeBnMtaMUa4mQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});